In [37]:
import random
from math import *
import operator
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline 

import seaborn as sns
sns.set(style="white", color_codes=True)

from pandas.plotting import scatter_matrix

from sklearn import model_selection
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.ensemble import RandomForestClassifier



In [38]:
location1 = r"E:\Python\Machine Learning\datasets\iris_train_RF.csv"
location2 = r"E:\Python\Machine Learning\datasets\iris_test_RF.csv"

In [39]:
# load the training data from iris.txt
df_train = pd.read_csv(location1 )
df_test = pd.read_csv(location2 )

In [40]:
df_test

class  petal_length  petal_width  sepal_length  sepal_width
0    Iris-virginica           6.6          2.1           7.6          3.0
1    Iris-virginica           6.3          1.8           7.3          2.9
2    Iris-virginica           5.5          2.1           6.8          3.0
3    Iris-virginica           5.1          2.4           5.8          2.8
4    Iris-virginica           5.3          2.3           6.4          3.2
5    Iris-virginica           6.7          2.2           7.7          3.8
6    Iris-virginica           4.9          2.0           5.6          2.8
7    Iris-virginica           4.9          1.8           6.3          2.7
8    Iris-virginica           4.9          1.8           6.1          3.0
9    Iris-virginica           5.8          1.6           7.2          3.0
10   Iris-virginica           6.4          2.0           7.9          3.8
11   Iris-virginica           5.6          2.2           6.4          2.8
12   Iris-virginica           5.4          2.1           6.9          3.1
13   Iris-virginica           5.6          2.4           6.7          3.1
14   Iris-virginica           5.1          1.8           5.9          3.0
15  Iris-versicolor           4.0          1.3           5.5          2.3
16  Iris-versicolor           4.5          1.3           5.7          2.8
17  Iris-versicolor           4.6          1.3           6.6          2.9
18  Iris-versicolor           3.9          1.4           5.2          2.7
19  Iris-versicolor           4.2          1.5           5.9          3.0
20  Iris-versicolor           4.5          1.5           5.6          3.0
21  Iris-versicolor           4.7          1.2           6.1          2.8
22  Iris-versicolor           4.3          1.3           6.4          2.9
23  Iris-versicolor           3.9          1.2           5.8          2.7
24  Iris-versicolor           4.7          1.5           6.7          3.1
25  Iris-versicolor           4.4          1.3           6.3          2.3
26  Iris-versicolor           4.0          1.3           5.5          2.5
27  Iris-versicolor           4.6          1.4           6.1          3.0
28  Iris-versicolor           4.0          1.2           5.8          2.6
29  Iris-versicolor           4.3          1.3           6.2          2.9
30      Iris-setosa           1.4          0.2           5.1          3.5
31      Iris-setosa           1.7          0.4           5.4          3.9
32      Iris-setosa           1.4          0.3           4.6          3.4
33      Iris-setosa           1.1          0.1           4.3          3.0
34      Iris-setosa           1.2          0.2           5.8          4.0
35      Iris-setosa           1.7          0.2           5.4          3.4
36      Iris-setosa           1.7          0.5           5.1          3.3
37      Iris-setosa           1.6          0.2           4.7          3.2
38      Iris-setosa           1.6          0.2           4.8          3.1
39      Iris-setosa           1.5          0.1           4.9          3.1
40      Iris-setosa           1.2          0.2           5.0          3.2
41      Iris-setosa           1.3          0.2           4.4          3.0
42      Iris-setosa           1.3          0.3           5.0          3.5
43      Iris-setosa           1.3          0.3           4.5          2.3
44      Iris-setosa           1.5          0.2           5.3          3.7

In [41]:
# data has to be in a numpy array in order for the random forest algorithm to except it!
cols = ['petal_length', 'petal_width', 'sepal_length', 'sepal_width']
colsRes = ['class']
#trainArr = df_train.as_matrix(cols)    # training array
#trainRes = df_train.as_matrix(colsRes) # training results

In [42]:
# the above can be achieved by the following way too.

trainArr = df_train[cols].values
trainRes = df_train[colsRes].values.ravel()

In [43]:
print(trainArr[:5])
print(trainRes[:5])

[[5.5 1.8 6.4 3.1]
 [5.9 2.3 6.8 3.2]
 [5.4 2.3 6.2 3.4]
 [4.8 1.8 6.  3. ]
 [5.1 2.3 6.9 3.1]]
['Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica']


In [44]:
# Training!
from sklearn.ensemble import RandomForestClassifier

# 100 decision trees is a good enough number
clf = RandomForestClassifier(n_estimators=100,oob_score=True)

In [45]:
# finally, we fit the data to the algorithm!!! :)
clf.fit(trainArr, trainRes)          

RandomForestClassifier(oob_score=True)

In [46]:
df_test.head()

class  petal_length  petal_width  sepal_length  sepal_width
0  Iris-virginica           6.6          2.1           7.6          3.0
1  Iris-virginica           6.3          1.8           7.3          2.9
2  Iris-virginica           5.5          2.1           6.8          3.0
3  Iris-virginica           5.1          2.4           5.8          2.8
4  Iris-virginica           5.3          2.3           6.4          3.2

In [50]:
## Testing!

# put the test results in the same format!
#testArr = df_test.as_matrix(cols)
testArr = df_test.drop(['predictions',"class"] ,axis=1).values

results = clf.predict(testArr)

In [51]:
# add it back to the dataframe, so we can compare side-by-side

df_test['predictions'] = results
df_test.head()

class  petal_length  petal_width  sepal_length  sepal_width  \
0  Iris-virginica           6.6          2.1           7.6          3.0   
1  Iris-virginica           6.3          1.8           7.3          2.9   
2  Iris-virginica           5.5          2.1           6.8          3.0   
3  Iris-virginica           5.1          2.4           5.8          2.8   
4  Iris-virginica           5.3          2.3           6.4          3.2   

      predictions  
0  Iris-virginica  
1  Iris-virginica  
2  Iris-virginica  
3  Iris-virginica  
4  Iris-virginica

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
5      Iris-virginica
6      Iris-virginica
7      Iris-virginica
8      Iris-virginica
9      Iris-virginica
10     Iris-virginica
11     Iris-virginica
12     Iris-virginica
13     Iris-virginica
14     Iris-virginica
15    Iris-versicolor
16    Iris-versicolor
17    Iris-versicolor
18    Iris-versicolor
19    Iris-versicolor
20    Iris-versicolor
21    Iris-versicolor
22    Iris-versicolor
23    Iris-versicolor
24    Iris-versicolor
25    Iris-versicolor
26    Iris-versicolor
27    Iris-versicolor
28    Iris-versicolor
29    Iris-versicolor
30        Iris-setosa
31        Iris-setosa
32        Iris-setosa
33        Iris-setosa
34        Iris-setosa
35        Iris-setosa
36        Iris-setosa
37        Iris-setosa
38        Iris-setosa
39        Iris-setosa
40        Iris-setosa
41        Iris-setosa
42        Iris-setosa
43        Iris-setosa
44        Iris-setosa
Name: clas

In [52]:
testArr

array([[6.6, 2.1, 7.6, 3. ],
       [6.3, 1.8, 7.3, 2.9],
       [5.5, 2.1, 6.8, 3. ],
       [5.1, 2.4, 5.8, 2.8],
       [5.3, 2.3, 6.4, 3.2],
       [6.7, 2.2, 7.7, 3.8],
       [4.9, 2. , 5.6, 2.8],
       [4.9, 1.8, 6.3, 2.7],
       [4.9, 1.8, 6.1, 3. ],
       [5.8, 1.6, 7.2, 3. ],
       [6.4, 2. , 7.9, 3.8],
       [5.6, 2.2, 6.4, 2.8],
       [5.4, 2.1, 6.9, 3.1],
       [5.6, 2.4, 6.7, 3.1],
       [5.1, 1.8, 5.9, 3. ],
       [4. , 1.3, 5.5, 2.3],
       [4.5, 1.3, 5.7, 2.8],
       [4.6, 1.3, 6.6, 2.9],
       [3.9, 1.4, 5.2, 2.7],
       [4.2, 1.5, 5.9, 3. ],
       [4.5, 1.5, 5.6, 3. ],
       [4.7, 1.2, 6.1, 2.8],
       [4.3, 1.3, 6.4, 2.9],
       [3.9, 1.2, 5.8, 2.7],
       [4.7, 1.5, 6.7, 3.1],
       [4.4, 1.3, 6.3, 2.3],
       [4. , 1.3, 5.5, 2.5],
       [4.6, 1.4, 6.1, 3. ],
       [4. , 1.2, 5.8, 2.6],
       [4.3, 1.3, 6.2, 2.9],
       [1.4, 0.2, 5.1, 3.5],
       [1.7, 0.4, 5.4, 3.9],
       [1.4, 0.3, 4.6, 3.4],
       [1.1, 0.1, 4.3, 3. ],
       [1.2, 0

In [35]:
clf.oob_score

True

In [36]:
clf.oob_score_

0.9238095238095239

In [19]:
cond_false=df_test["class"]!=df_test["predictions"]

In [20]:
cond_false

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
dtype: bool

In [21]:
df_test.shape

(45, 6)

In [22]:
df_test["class"]==df_test["predictions"]

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9     False
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
42     True
43     True
44     True
dtype: bool

In [60]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve, auc

In [61]:
n_estimators = [1, 2, 4, 8, 16, 32, 64, 100, 200]

train_results = []
test_results = []

for estimator in n_estimators:
   rf = RandomForestClassifier(n_estimators=estimator, n_jobs=-1)
   rf.fit(trainArr, trainRes)
   
   # predict for all the training samples in X_train
   train_pred = rf.predict(trainArr)
   false_positive_rate, true_positive_rate, thresholds = roc_curve(trainRes, train_pred)
    
   roc_auc = auc(false_positive_rate, true_positive_rate)
   train_results.append(roc_auc)
   
   # predict for all the training samples in X_test
   y_pred = rf.predict(testArr)
   false_positive_rate, true_positive_rate, thresholds = roc_curve(df_test['class'], y_pred)
    
   roc_auc = auc(false_positive_rate, true_positive_rate)
   test_results.append(roc_auc)

ValueError: multiclass format is not supported