In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

<!-- This code generates two 3x3 NumPy arrays (arr1 and arr2) with random integers between 1 and 2 (inclusive). The purpose of this code is to create sample arrays for demonstrating various NumPy operations and functionalities. -->

In [3]:
arr1

array([[1, 1, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [4]:
arr1.flatten() #Return a copy of the array collapsed into one dimension.

array([1, 1, 2, 1, 1, 1, 2, 1, 2])

In [5]:
#expand dimesnion
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [6]:
arr.ndim

1

In [7]:
np.expand_dims(arr, axis = 0) #increases the dimension by 1 at provoided axis

array([[1, 2, 3, 4]])

The np.expand_dims(arr, axis=0) function increases the number of dimensions of the NumPy array arr by inserting a new axis at the specified position axis=0. This means that a new dimension of length 1 is added at the beginning of the array's shape.
The purpose of this operation is to allow certain operations that require arrays with a specific number of dimensions. For example, some operations in NumPy require the input arrays to have the same number of dimensions, so np.expand_dims can be used to add a new axis to one of the arrays, making their shapes compatible.

In [18]:
np.expand_dims(arr, axis = 1)

array([[1],
       [2],
       [3],
       [4]])

In [23]:
np.expand_dims(arr, axis = 1)

2

The np.expand_dims(arr, axis=1) function also increases the number of dimensions of the NumPy array arr, but in this case, it inserts a new axis at the position axis=1. This means that a new dimension of length 1 is added after the first dimension of the array's shape.
The purpose of this operation is similar to np.expand_dims(arr, axis=0), but it adds the new dimension in a different position. This can be useful when you need to perform operations that require arrays with a specific shape or number of dimensions, and you need to modify the shape of your array accordingly.

In [22]:
np.expand_dims(arr, axis = 1).ndim

3

The code np.expand_dims(arr, axis=1).ndim returns the number of dimensions (axes) in the resulting array after applying the np.expand_dims operation with axis=1.
The purpose of this code is to check the dimensionality of the new array created by np.expand_dims(arr, axis=1). By adding a new axis at position 1, the dimensionality of the original array is increased by 1.

In [24]:
arr

array([1, 2, 3, 4])

In [25]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
arr.ndim

2

In [27]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
np.expand_dims(arr, axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [32]:
np.expand_dims(arr, axis=0).ndim

3

In [33]:
a = np.array([[1], [2], [3]])

In [34]:
a

array([[1],
       [2],
       [3]])

In [35]:
a.ndim

2

In [36]:
np.squeeze(a) #Remove axes of length one from `a`

array([1, 2, 3])

In [38]:
a

array([[1],
       [2],
       [3]])

In [39]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [40]:
arr1

array([[1, 1, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [41]:
np.repeat(arr1, 2)

array([1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2])

In [46]:
np.repeat(arr1, 2, axis=0)

array([[1, 1, 2],
       [1, 1, 2],
       [1, 1, 1],
       [1, 1, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [48]:
np.repeat(arr1, 3, axis=0)

array([[1, 1, 2],
       [1, 1, 2],
       [1, 1, 2],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [53]:
np.repeat(arr1, 3, axis=1)

array([[1, 1, 1, 1, 1, 1, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 2, 2, 2]])

In [54]:
a

array([[1],
       [2],
       [3]])

In [55]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [56]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [57]:
c = np.array([[1,2], [3, 4], [5,6], [7,8]])

In [58]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [59]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [63]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [64]:
arr1

array([[1, 1, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [65]:
arr2

array([[2, 1, 2],
       [2, 1, 2],
       [1, 1, 2]])

In [66]:
arr1 + arr2

array([[3, 2, 4],
       [3, 2, 3],
       [3, 2, 4]])

In [67]:
arr1-arr2

array([[-1,  0,  0],
       [-1,  0, -1],
       [ 1,  0,  0]])

In [68]:
arr1 * arr2

array([[2, 1, 4],
       [2, 1, 2],
       [2, 1, 4]])

In [69]:
arr1 > arr2

array([[False, False, False],
       [False, False, False],
       [ True, False, False]])

In [70]:
arr1

array([[1, 1, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [71]:
~arr1  # The tilde ~ operator in NumPy is used for bitwise NOT operation. When applied to a boolean array, it inverts the values (i.e., True becomes False and False becomes True).

array([[-2, -2, -3],
       [-2, -2, -2],
       [-3, -2, -3]])

In [72]:
#operations on numpy string array

In [73]:
d = np.array(["azad", "skills"])

In [74]:
d

array(['azad', 'skills'], dtype='<U6')

In [75]:
np.char.upper(d)

array(['AZAD', 'SKILLS'], dtype='<U6')

In [76]:
np.char.capitalize(d)

array(['Azad', 'Skills'], dtype='<U6')

In [77]:
#mathematical functions

In [78]:
arr1

array([[1, 1, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [79]:
np.sin(arr1)  # The np.sin function in NumPy is used to compute the trigonometric sine of each element in the input array. This function expects the input to be in radians and returns the sine of each element.

array([[0.84147098, 0.84147098, 0.90929743],
       [0.84147098, 0.84147098, 0.84147098],
       [0.90929743, 0.84147098, 0.90929743]])

In [80]:
np.cos(arr1) #The np.cos function in NumPy is used to compute the trigonometric cosine of each element in the input array. This function expects the input to be in radians and returns the cosine of each element.

array([[ 0.54030231,  0.54030231, -0.41614684],
       [ 0.54030231,  0.54030231,  0.54030231],
       [-0.41614684,  0.54030231, -0.41614684]])

In [82]:
np.tan(arr1) #The np.tan function in NumPy is used to compute the trigonometric tangent of each element in the input array. This function expects the input to be in radians and returns the tangent of each element.

array([[ 1.55740772,  1.55740772, -2.18503986],
       [ 1.55740772,  1.55740772,  1.55740772],
       [-2.18503986,  1.55740772, -2.18503986]])

In [83]:
np.log10(arr1) #The np.log10 function in NumPy is used to compute the base 10 logarithm of each element in the input array.

array([[0.     , 0.     , 0.30103],
       [0.     , 0.     , 0.     ],
       [0.30103, 0.     , 0.30103]])

In [62]:
np.exp(arr1) #The np.exp function in NumPy is used to compute the exponential of each element in the input array.

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183]])

In [63]:
np.power(arr1, 3) #The np.power function in NumPy is used to compute the power of each element in the input array.

array([[8, 8, 8],
       [8, 8, 8],
       [1, 8, 1]], dtype=int32)

In [64]:
np.mean(arr1) #The np.mean function in NumPy is used to compute the arithmetic mean of the input array.

1.7777777777777777

In [65]:
np.max(arr1) #The np.max function in NumPy is used to compute the maximum value of the input array.

2

In [66]:
np.min(arr1) #The np.min function in NumPy is used to compute the minimum value of the input array.

1

In [67]:
np.std(arr1) #The np.std function in NumPy is used to compute the standard deviation of the input array.

0.41573970964154905

In [68]:
np.var(arr1)    #The np.var function in NumPy is used to compute the variance of the input array.

0.1728395061728395

In [69]:
arr1-arr2 #The np.subtract function in NumPy is used to subtract the elements of one array from another.

array([[1, 1, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [70]:
np.subtract(arr1, arr2) #The np.subtract function in NumPy is used to subtract the elements of one array from another.

array([[1, 1, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [71]:
arr1 *arr2 #The np.multiply function in NumPy is used to multiply the elements of one array with another.

array([[2, 2, 4],
       [2, 4, 2],
       [1, 4, 1]])

In [72]:
np.multiply(arr1, arr2) #The np.multiply function in NumPy is used to multiply the elements of one array with another.

array([[2, 2, 4],
       [2, 4, 2],
       [1, 4, 1]])

In [73]:
np.mod(arr1, arr2) #return elment wise remainder

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [74]:
np.sqrt(arr1) #The np.sqrt function in NumPy is used to compute the square root of each element in the input array.

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        ]])

In [86]:
#sort search

e = np.array([5, 6, 1, 2])

In [87]:
e

array([5, 6, 1, 2])

In [88]:
np.sort(e)

array([1, 2, 5, 6])

In [89]:
f = np.array([5, 199, 200, 6, 7, 8])

In [90]:
f

array([  5, 199, 200,   6,   7,   8])

In [1]:
np.sort(f)

NameError: name 'np' is not defined

: 

In [103]:
np.searchsorted(f, 7) #Find indices where elements should be inserted to maintain order.

1

In [93]:
f = np.array([5, 199, 200, 6, 7, 0, 0, 0, 8])

In [94]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [84]:
np.count_nonzero(f)

6

In [85]:
f[f > 0]

array([  5, 199, 200,   6,   7,   8])

In [86]:
np.where(f>0)

(array([0, 1, 2, 3, 4, 8], dtype=int64),)

In [87]:
np.extract(f>0, f)

array([  5, 199, 200,   6,   7,   8])

In [88]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [89]:
f.byteswap()

array([  83886080, -956301312, -939524096,  100663296,  117440512,
                0,          0,          0,  134217728])

In [90]:
#matrix>> 2d array

import numpy.matlib as nm

In [91]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [92]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [93]:
#numpy linear algebra

arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(1, 10, (3, 3))

In [94]:
arr1

array([[6, 4, 9],
       [7, 6, 2],
       [8, 6, 1]])

In [95]:
arr2

array([[9, 1, 7],
       [2, 8, 9],
       [6, 5, 3]])

In [96]:
arr1 @ arr2

array([[116,  83, 105],
       [ 87,  65, 109],
       [ 90,  61, 113]])

In [97]:
arr1

array([[6, 4, 9],
       [7, 6, 2],
       [8, 6, 1]])

In [98]:
np.linalg.det(arr1)

-54.00000000000001

In [99]:
np.linalg.inv(arr1)

array([[ 0.11111111, -0.92592593,  0.85185185],
       [-0.16666667,  1.22222222, -0.94444444],
       [ 0.11111111,  0.07407407, -0.14814815]])

In [100]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [101]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [102]:
b = np.array([16, 8, 0])

In [103]:
b

array([16,  8,  0])

In [104]:
np.linalg.solve(a, b)

array([2.59630607, 0.84432718, 2.21635884])