#### sklearn.neighbors.KDTree
Parameters:	

- X : array-like, shape = [n_samples, n_features]
n_samples is the number of points in the data set, and n_features is the dimension of the parameter space. 

- leaf_size : positive integer (default = 40)
Number of points at which to switch to brute-force. 

- metric : string or DistanceMetric object
the distance metric to use for the tree. Default=’minkowski’ with p=2 (that is, a euclidean metric). 

In [1]:
import numpy as np
from sklearn.neighbors import KDTree
import pickle

In [2]:
np.random.seed(0)
X = np.random.random((10, 3))  # 10 points in 3 dimensions
X

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194]])

In [3]:
tree = KDTree(X, leaf_size=2, metric='euclidean')              
s = pickle.dumps(tree)  

In [ ]:
# Some time later ... load the tree back in

In [4]:
tree_copy = pickle.loads(s) 

In [5]:
tree_copy.valid_metrics

['euclidean',
 'l2',
 'minkowski',
 'p',
 'manhattan',
 'cityblock',
 'l1',
 'chebyshev',
 'infinity']

In [6]:
dist, ind = tree_copy.query(X[:1], k=3)   

print(ind)   # indices of 3 closest neighbors
print(dist)  # distances to 3 closest neighbors

[[0 3 1]]
[[0.         0.19662693 0.29473397]]
