In [24]:
import pandas as pd
import numpy as np
import math

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [25]:
df = pd.read_csv (r'C:\Users\User\Desktop\Machine Learning\datasets\Auto.csv')

In [26]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [27]:
# We don’t need the name column, so let’s remove this
df = df.drop('name', axis=1)

In [28]:
# Also note that the column "origin" is where the car came from and 
# this is an ordinal categorical variable so we will need to create the dummy binary variables 
# for this
df['origin'].unique()

array([1, 3, 2], dtype=int64)

In [29]:
df['origin'] = df['origin'].replace({1: 'america', 2: 'europe', 3: 'asia'})

In [30]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

    origin  
0  america  
1  america  
2  america  
3  america  
4  america

In [31]:
df = pd.get_dummies(df, columns=['origin'])

In [32]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin_america  origin_asia  origin_europe  
0               1            0              0  
1               1            0              0  
2               1            0              0  
3               1            0              0  
4               1            0              0

In [41]:
df.isna().sum()

mpg               0
cylinders         0
displacement      0
horsepower        0
weight            0
acceleration      0
year              0
origin_america    0
origin_asia       0
origin_europe     0
dtype: int64

In [42]:
df.shape

(397, 10)

In [43]:
# check for missing
df = df.replace('?', np.nan)
df = df.dropna()

In [44]:
df.shape

(392, 10)

In [47]:
df

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
5    15.0          8         429.0        198    4341          10.0    70   
6    14.0          8         454.0        220    4354           9.0    70   
7    14.0          8         440.0        215    4312           8.5    70   
8    14.0          8         455.0        225    4425          10.0    70   
9    15.0          8         390.0        190    3850           8.5    70   
10   15.0          8         383.0        170    3563          10.0    70   
11   14.0          8         340.0        160    3609           8.0    70   
12   15.0          8         400.0        150    3761           9.5    70   
13   14.0          8         455.0        225    3086          10.0    70   
14   24.0          4         113.0         95    2372          15.0    70   
15   22.0          6         198.0         95    2833          15.5    70   
16   18.0          6         199.0         97    2774          15.5    70   
17   21.0          6         200.0         85    2587          16.0    70   
18   27.0          4          97.0         88    2130          14.5    70   
19   26.0          4          97.0         46    1835          20.5    70   
20   25.0          4         110.0         87    2672          17.5    70   
21   24.0          4         107.0         90    2430          14.5    70   
22   25.0          4         104.0         95    2375          17.5    70   
23   26.0          4         121.0        113    2234          12.5    70   
24   21.0          6         199.0         90    2648          15.0    70   
25   10.0          8         360.0        215    4615          14.0    70   
26   10.0          8         307.0        200    4376          15.0    70   
27   11.0          8         318.0        210    4382          13.5    70   
28    9.0          8         304.0        193    4732          18.5    70   
29   27.0          4          97.0         88    2130          14.5    71   
..    ...        ...           ...        ...     ...           ...   ...   
367  28.0          4         112.0         88    2605          19.6    82   
368  27.0          4         112.0         88    2640          18.6    82   
369  34.0          4         112.0         88    2395          18.0    82   
370  31.0          4         112.0         85    2575          16.2    82   
371  29.0          4         135.0         84    2525          16.0    82   
372  27.0          4         151.0         90    2735          18.0    82   
373  24.0          4         140.0         92    2865          16.4    82   
374  36.0          4         105.0         74    1980          15.3    82   
375  37.0          4          91.0         68    2025          18.2    82   
376  31.0          4          91.0         68    1970          17.6    82   
377  38.0          4         105.0         63    2125          14.7    82   
378  36.0          4          98.0         70    2125          17.3    82   
379  36.0          4         120.0         88    2160          14.5    82   
380  36.0          4         107.0         75    2205          14.5    82   
381  34.0          4         108.0         70    2245          16.9    82   
382  38.0          4          91.0         67    1965          15.0    82   
383  32.0          4          91.0         67    1965          15.7    82   
384  38.0          4          91.0         67    1995          16.2    82   
385  25.0          6         181.0        110    2945          16.4    82   
386  38.0          6         262.0         85    3015          17.0    82   
38

In [50]:
# extract the data, into numpy array
X = df.drop('mpg', axis=1)
print(X.head())
y = df[['mpg']]

   cylinders  displacement horsepower  weight  acceleration  year  \
0          8         307.0        130    3504          12.0    70   
1          8         350.0        165    3693          11.5    70   
2          8         318.0        150    3436          11.0    70   
3          8         304.0        150    3433          12.0    70   
4          8         302.0        140    3449          10.5    70   

   origin_america  origin_asia  origin_europe  
0               1            0              0  
1               1            0              0  
2               1            0              0  
3               1            0              0  
4               1            0              0  


In [14]:
# split our data into a training and test set:
# Split X and y into X_
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [15]:
# Instantiate the linear regression model
linreg = LinearRegression()
linreg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
# contains an array of intercepts (β0 values)
linreg.intercept_ 

array([-19.80918385])

In [17]:
# view the coefficients of the model
linreg.coef_

array([[-0.24633756,  0.02387034, -0.00601724, -0.00733643,  0.21897778,
         0.78518011, -1.76249341,  0.80962692,  0.95286649]])

In [18]:
# view the coefficients of the model
for idx, name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(name, linreg.coef_[0][idx]))

The coefficient for cylinders is -0.2463375586996167
The coefficient for displacement is 0.02387033830714957
The coefficient for horsepower is -0.006017238617773325
The coefficient for weight is -0.007336432943899315
The coefficient for acceleration is 0.21897778104124824
The coefficient for year is 0.7851801072779493
The coefficient for origin_america is -1.7624934092199247
The coefficient for origin_asia is 0.8096269190858489
The coefficient for origin_europe is 0.9528664901340749


In [19]:
# So we can write our linear model as:

# Y=−19.81 – 0.25×X1 + 0.02×X2 –0.01×X3 –0.01×X4 +0.22×X5 +0.78×X6 –1.76×X7 +0.81×X8 +0.95×X9

# Note that, because we’ve not done any feature scaling or dimensionality reduction, 
# we can’t say anything about the relative importance of each of our features given these 
# coefficients because the features are not of the same scale.

In [20]:
# Scoring Model
# A common method of measuring the accuracy of regression models is to use the R2 statistic.

# The R2 statistic is defined as follows:

# R2=1–RSSTSS
# The RSS (Residual sum of squares) measures the variability left unexplained after performing 
# the regression
# The TSS measues the total variance in Y
# Therefore the R2 statistic measures proportion of variability in Y that is explained by X 
# using our model

linreg.score(X_test, y_test)

0.82852313164597735

In [21]:
# So in our model, 82.85% of the variability in Y can be explained using X

In [22]:
y_predict = linreg.predict(X_test)

linreg_mse = mean_squared_error(y_predict, y_test)

linreg_mse

12.230963834602667

In [23]:
math.sqrt(linreg_mse)

3.4972794904900963

In [24]:
# So we are an average of 3.50 mpg away from the ground truth mpg when making predictions on 
# our test set.

In [24]:
# Making Predictions
# We can use our model to predict the miles per gallon for another, unseen car
# Cylinders – 4
# Displacement – 121
# Horsepower – 110
# Weight – 2800
# Acceleration – 15.4
# Year – 81
# Origin – Asia

# origin_america	origin_asia	origin_europe
# 0 - 1 - 0
linreg.predict([[4, 121, 110, 2800, 15.4, 81, 0, 1, 0]])

array([[ 28.6713418]])